"""empty message

Revision ID: 403ac643c539
Revises: c6501ecb2f4f
Create Date: 2018-11-20 11:02:08.031634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403ac643c539'
down_revision = 'c6501ecb2f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('m_name', sa.String(length=128), nullable=True),
    sa.Column('m_name_en', sa.String(length=256), nullable=True),
    sa.Column('m_director', sa.String(length=64), nullable=True),
    sa.Column('m_leading_role', sa.String(length=256), nullable=True),
    sa.Column('m_duration', sa.Integer(), nullable=True),
    sa.Column('m_country', sa.String(length=64), nullable=True),
    sa.Column('m_type', sa.String(length=64), nullable=True),
    sa.Column('m_screen_model', sa.String(length=32), nullable=True),
    sa.Column('m_open_day', sa.DateTime(), nullable=True),
    sa.Column('m_introduce', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
