"""empty message

Revision ID: 4646df91fb7d
Revises: 6f384bc758cf
Create Date: 2018-11-20 16:41:56.806299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4646df91fb7d'
down_revision = '6f384bc758cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('h_number', sa.String(length=32), nullable=True),
    sa.Column('h_type', sa.Integer(), nullable=True),
    sa.Column('h_seats', sa.String(length=256), nullable=True),
    sa.Column('h_cinema', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['h_cinema'], ['cinema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    # ### end Alembic commands ###
