"""empty message

Revision ID: 92bb9bb3cc92
Revises: 
Create Date: 2018-11-19 15:32:10.037578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bb9bb3cc92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('a_name', sa.String(length=32), nullable=True),
    sa.Column('_a_password', sa.String(length=256), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('p_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p_name')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('u_permission_id', sa.Integer(), nullable=True),
    sa.Column('u_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['u_user_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission')
    op.drop_table('permission')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
