"""empty message

Revision ID: 98ea4ee8e378
Revises: 9f6901f2df42
Create Date: 2018-11-21 15:02:23.223181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ea4ee8e378'
down_revision = '9f6901f2df42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewer_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('v_phone', sa.String(length=32), nullable=True),
    sa.Column('_v_password', sa.String(length=256), nullable=True),
    sa.Column('v_permission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('v_phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewer_user')
    # ### end Alembic commands ###
