"""empty message

Revision ID: 9f6901f2df42
Revises: 4646df91fb7d
Create Date: 2018-11-21 09:54:52.951599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6901f2df42'
down_revision = '4646df91fb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pai_dang',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('p_movie', sa.Integer(), nullable=True),
    sa.Column('p_hall', sa.Integer(), nullable=True),
    sa.Column('p_time_start', sa.DateTime(), nullable=True),
    sa.Column('p_time_end', sa.DateTime(), nullable=True),
    sa.Column('p_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['p_hall'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['p_movie'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pai_dang')
    # ### end Alembic commands ###
