"""empty message

Revision ID: d547ce21d678
Revises: 403ac643c539
Create Date: 2018-11-20 15:36:38.330016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd547ce21d678'
down_revision = '403ac643c539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('o_user', sa.Integer(), nullable=True),
    sa.Column('o_status', sa.Integer(), nullable=True),
    sa.Column('o_time', sa.DateTime(), nullable=True),
    sa.Column('o_movie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['o_movie'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['o_user'], ['cinema_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
