"""empty message

Revision ID: e4702973e92a
Revises: 92bb9bb3cc92
Create Date: 2018-11-19 16:39:09.847789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4702973e92a'
down_revision = '92bb9bb3cc92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_u_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('p_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('p_name')
    )
    op.create_table('cinema_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('c_name', sa.String(length=32), nullable=True),
    sa.Column('_c_password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('c_name')
    )
    op.create_table('cinema_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('u_permission_id', sa.Integer(), nullable=True),
    sa.Column('u_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_permission_id'], ['c_u_permission.id'], ),
    sa.ForeignKeyConstraint(['u_user_id'], ['cinema_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_permission')
    op.drop_table('cinema_user')
    op.drop_table('c_u_permission')
    # ### end Alembic commands ###
